# Generated by Django 3.1.4 on 2021-02-06 18:08

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='class',
            name='technologies',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('html', 'HTML'), ('css', 'CSS'), ('js', 'JavaScript'), ('jq', 'JQuery'), ('re', 'React'), ('an', 'Angular'), ('vu', 'Vue'), ('php', 'PHP'), ('lv', 'Laravel'), ('sy', 'Symfony'), ('no', 'Node.js'), ('ex', 'Express.js'), ('my', 'MySQL'), ('ps', 'PostgresQl'), ('md', 'MongoDB'), ('py', 'Python'), ('dj', 'Django'), ('fl', 'Flask'), ('ja', 'Java'), ('c', 'C'), ('cpp', 'C++'), ('cs', 'C#'), ('oc', 'Objective-C'), ('sw', 'Swift'), ('go', 'Go'), ('rs', 'Rust'), ('rb', 'Ruby'), ('rr', 'Ruby On rails')], max_length=87),
        ),
        migrations.AlterField(
            model_name='class',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='tutor.user'),
        ),
    ]
