# Generated by Django 3.1.4 on 2021-02-08 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tutor', '0002_auto_20210206_1808'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='applicants',
        ),
        migrations.AddField(
            model_name='class',
            name='applicants',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='hired',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='class',
            name='user',
            field=models.CharField(max_length=100),
        ),
    ]
